name: Schedule Workflow
on: 
  schedule:
    - cron: '* * * * *'
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: print build
        run: echo 'build'
  test:
    runs-on: windows-latest
    steps:
      - name: print test-chrome
        run: echo 'test chrome'
      - name: print test-edge
        run: echo 'test edge'
  deploy:
    runs-on: windows-latest
    steps:
      - name: print deploy
        run: echo 'deploy'
